name: Run E2E Tests
description: This action sets up playwright browsers and runs e2e tests.

runs:
  using: composite
  steps:
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Run E2E tests
      run: pnpm run test:e2e

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
