name: Deploy Vercel 
description: Deploy Vercel in two modes

inputs:
  vercel-token:
    description: 'Vercel token'
    required: true
  mode:
    description: 'Deployment mode'
    required: true
    default: 'production'

runs:
  using: composite
  steps:
    - name: Install Vercel CLI
      run: pnpm add -g vercel@canary
      shell: bash

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=${{ inputs.mode }} --token=${{ inputs.vercel-token }}
      shell: bash

    - name: Build for Vercel
      run: vercel build --token=${{ inputs.vercel-token }}
      shell: bash
    
    - name: Deploy to Vercel
      run: |
        DEPLOY_OUTPUT="$(vercel deploy --prebuilt --token=${{ inputs.vercel-token }})"
        DEPLOY_URL="$(echo "$DEPLOY_OUTPUT" | grep http | tail -n 1)"
        echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
      shell: bash