name: Deploy Vercel
description: Deploy Vercel in two modes

inputs:
  vercel-token:
    description: 'Vercel token'
    required: true
  mode:
    description: 'Deployment mode'
    required: true
    default: 'production'

runs:
  using: composite
  steps:
    - name: Install Vercel CLI
      run: pnpm add -g vercel@canary

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build for Vercel
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
    
    - name: Deploy to Vercel
      run: |
        DEPLPY_OUTPUT="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
        DEPLOY_URL="$(echo "$DEPLPY_OUTPUT" | grep http | tail -n 1)"
        echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV

    - name: Comment with Preview URL
      uses: actions/github-script@v7
      with:
        script: |
          const { DEPLOY_URL } = process.env;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🔍 Preview URL: ${DEPLOY_URL}`
          })