name: Deploy - AWS

on:
  workflow_dispatch:

jobs:
  deploy-aws:
    environment:
      name: 'Production'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node and PNPM
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: |
          echo "VITE_ENVIRONMENT=production" >> .env
          pnpm run build

      - name: Lint code
        run: pnpm run lint

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS
        run: aws s3 sync dist s3://confticket
