name: Deploy on push

on:
  push:
    branches:
      - master

jobs:
  deploy-netlify:
    uses: ./.github/workflows/deploy_netlify.yml
    secrets: inherit

  deploy-vercel:
    needs: deploy-netlify
    uses: ./.github/workflows/deploy_vercel.yml
    secrets: inherit