name: Deploy - Vercel

on:
  workflow_call:
    secrets:
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true

jobs:
  deploy-vercel:
    environment:
      name: 'Staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node and PNPM
        uses: ./.github/actions/setup-node

      - name: Lint code
        run: npm run lint

      - name: Build app
        run: npm run build

      - name: Deploy app to Vercel production env
        uses: ./.github/actions/deploy-vercel
        with:
          mode: 'production'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
