name: Deploy - AWS

on:
  workflow_dispatch:

jobs:
  deploy-aws:
    environment:
      name: 'Production'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node and PNPM
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: |
          echo "VITE_ENVIRONMENT=production" >> .env
          pnpm run build

      - name: Lint code
        run: pnpm run lint

      - name: Deploy to AWS
        run: aws s3 sync dist s3://confticket
